name: Build and Push Container

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      push:
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["amd64", "arm64"]
    steps:
      # Install qemu
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # Enable podman cache
      - name: Cache podman storage
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~/.local/share/containers/storage
          key: podman-storage-${{ matrix.platform }}

      # Export arch
      - name: Export image name and arch
        run: |
          echo "IMAGE=${IMAGE}" >> ${GITHUB_ENV}
          echo "PLATFORM=${PLATFORM}" >> ${GITHUB_ENV}
          [ "${PLATFORM}" = "amd64" ] && echo "PODMAN_ARCH=linux/amd64" >> ${GITHUB_ENV} || true
          [ "${PLATFORM}" = "arm64" ] && echo "PODMAN_ARCH=linux/arm64/v8" >> ${GITHUB_ENV} || true
        env:
          PLATFORM: ${{ matrix.platform }}
          IMAGE: ${{ inputs.image }}

      - name: Build image with podman
        run: |
          podman build --platform "${{ env.PODMAN_ARCH }}" -f "${{ env.IMAGE }}/Dockerfile" -t "ghcr.io/erhardtconsulting/desktop-${{ env.IMAGE }}:build-${{ env.PLATFORM }}" "${{ env.IMAGE }}/"

      - name: Put container to oci
        run: |
          skopeo copy containers-storage:ghcr.io/erhardtconsulting/desktop-${{ env.IMAGE }}:build-${{ env.PLATFORM }} oci-archive:/tmp/${{ env.PLATFORM }}-oci.tar

      - name: Upload digest
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: ${{ env.IMAGE }}-build-${{ env.PLATFORM }}
          path: /tmp/${{ env.PLATFORM }}-oci.tar
          if-no-files-found: error
          retention-days: 7

  push:
    name: Push image
    runs-on: ubuntu-latest
    if: ${{ inputs.push }}
    needs: build
    steps:
      - name: Export image name
        run: |
          echo "IMAGE=${IMAGE}" >> ${GITHUB_ENV}
        env:
          IMAGE: ${{ inputs.image }}

      - name: Download amd64
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4
        with:
          name: ${{ env.IMAGE }}-build-amd64
          path: /tmp

      - name: Download arm64
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4
        with:
          name: ${{ env.IMAGE }}-build-arm64
          path: /tmp

      - name: Create multi-arch image
        run: |
          podman manifest create ghcr.io/erhardtconsulting/desktop-${{ env.IMAGE }}:manifest
          podman manifest add ghcr.io/erhardtconsulting/desktop-${{ env.IMAGE }}:manifest oci-archive:/tmp/arm64-oci.tar
          podman manifest add ghcr.io/erhardtconsulting/desktop-${{ env.IMAGE }}:manifest oci-archive:/tmp/amd64-oci.tar
          podman tag ghcr.io/erhardtconsulting/desktop-${{ env.IMAGE }}:manifest ghcr.io/erhardtconsulting/desktop-${{ env.IMAGE }}:latest

      - name: Push image to ghcr
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
        with:
          image: desktop-${{ env.IMAGE }}
          tags: latest
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io/erhardtconsulting