name: Build Xfce4 Container

on:
  pull_request:
    branches:
      - main
    paths:
      - 'xfce4/**'
      - '.github/workflows/build-xfce4-container.yaml'

permissions:
  contents: read
  packages: write

jobs:
  call-build-workflow:
    name: Build Xfce4
    uses: erhardtconsulting/desktop/.github/workflows/build-container.yaml@main
    with:
      image: xfce4
      push: false