name: Build and Push Base Container

on:
  pull_request:
    branches:
      - main
    paths:
      - 'base/**'
      - '.github/workflows/build-base-container.yaml'

permissions:
  contents: read
  packages: write

jobs:
  call-build-workflow:
    name: Build & Push Base
    uses: erhardtconsulting/desktop/.github/workflows/build-container.yaml@main
    with:
      image: base
      push: false