name: Build and Push xfce4 Container

on:
  push:
    branches:
      - main
    paths:
      - 'xfce4/**'
      - '.github/workflows/build-xfce4-container.yaml'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["amd64", "arm64"]
    steps:
      # Install qemu
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Enable podman cache
      - name: Cache podman storage
        uses: actions/cache@v3
        with:
          path: ~/.local/share/containers/storage
          key: podman-storage-${{ matrix.platform }}

      # Export arch
      - name: export architecture name (removing os prefix)
        run: |
          echo "PLATFORM=${PLATFORM}" >> ${GITHUB_ENV}
          [ "${PLATFORM}" = "amd64" ] && echo "PODMAN_ARCH=linux/amd64" >> ${GITHUB_ENV}
          [ "${PLATFORM}" = "arm64" ] && echo "PODMAN_ARCH=linux/arm64/v8" >> ${GITHUB_ENV}
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Build image with podman
        run: |
          podman build --platform ${{ env.PODMAN_ARCH }} -f "xfce4/Dockerfile" -t "ghcr.io/erhardtconsulting/desktop-xfce4:build-${{ env.PLATFORM }}" "xfce4/"

      - name: Put container to oci
        run: |
          skopeo copy containers-storage:ghcr.io/erhardtconsulting/desktop-xfce4:build-${{ env.PLATFORM }} oci-archive:/tmp/${{ env.PLATFORM }}-oci.tar

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: xfce4-build-${{ env.PLATFORM }}
          path: /tmp/${{ env.PLATFORM }}-oci.tar
          if-no-files-found: error
          retention-days: 7

  push:
    name: Push image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download amd64
        uses: actions/download-artifact@v4
        with:
          name: xfce4-build-amd64
          path: /tmp

      - name: Download arm64
        uses: actions/download-artifact@v4
        with:
          name: xfce4-build-arm64
          path: /tmp

      - name: Create multi-arch image
        run: |
          podman manifest create ghcr.io/erhardtconsulting/desktop-xfce4:manifest
          podman manifest add ghcr.io/erhardtconsulting/desktop-xfce4:manifest oci-archive:/tmp/arm64-oci.tar
          podman manifest add ghcr.io/erhardtconsulting/desktop-xfce4:manifest oci-archive:/tmp/amd64-oci.tar
          podman tag ghcr.io/erhardtconsulting/desktop-xfce4:manifest ghcr.io/erhardtconsulting/desktop-xfce4:latest

      - name: Push image to ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: desktop-xfce4
          tags: latest
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io/erhardtconsulting