name: Build and Push Base Container

on:
  push:
    branches:
      - main
    paths:
      - 'base/**'
      - '.github/workflows/build-base-container.yaml'

jobs:
  call-build-workflow:
    uses: erhardtconsulting/desktop/.github/workflows/build-container.yaml@main
    with:
      image: base