name: Build Xfce4-Full Container

on:
  pull_request:
    branches:
      - main
    paths:
      - 'xfce4-full/**'
      - '.github/workflows/build-xfce4-full-container.yaml'

permissions:
  contents: read
  packages: write

jobs:
  call-build-workflow:
    name: Build Xfce4-Full
    uses: erhardtconsulting/desktop/.github/workflows/build-container.yaml@main
    with:
      image: xfce4-full
      push: false